package fenetre;

import carnet.Carnet;
import connexion.Echange;
import exceptions.DataExceptions;
import fiche.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class FormMod extends javax.swing.JFrame {

    private Carnet carnet = new Carnet();
    private Echange echange = new Echange();

    public FormMod() {
        initComponents();
        if (carnet.recup(0) != null) {
            afficherF(carnet.recup(0));
        }
    }

    public Carnet getCarnet() {
        return carnet;
    }

    public Echange getEchange() {
        return echange;
    }

    private Vector initContact(Echange echange) throws DataExceptions {
        echange.connect();
        carnet.restore(echange);
        echange.close();
        //System.out.println(carnet);
        return carnet.getList();
    }

    private DefaultComboBoxModel initComboBox() {
        try {
            return new DefaultComboBoxModel(initContact(echange));
        } catch (DataExceptions ex) {
            ex.msgPrint();
        }
        return null;
        
    }

    private void afficherF(Connaissance f) {
        if (f.getType() == 0) {
            jrbConnais.setSelected(true);
            jlbMobile.setVisible(!jrbConnais.isSelected());
            jftMobile.setVisible(!jrbConnais.isSelected());
            jlbDateN.setVisible(!jrbConnais.isSelected());
            jftDateN.setVisible(!jrbConnais.isSelected());

            jftNom.setText(f.getNom());
            jftPrenom.setText(f.getPrenom());
            jftAdresse.setText(f.getAdresse());
            jftCodeP.setText(f.getCodePostal());
            jftVille.setText(f.getVille());
            jftTel.setText(f.getTel());
            jftMail.setText(f.getMail());
        }
        if (f.getType() == 1) {
            Ami fA = (Ami) f;//jcbChContact.getSelectedItem();
            jrbAmi.setSelected(true);
            jlbMobile.setVisible(jrbAmi.isSelected());
            jftMobile.setVisible(jrbAmi.isSelected());
            jlbDateN.setVisible(!jrbAmi.isSelected());
            jftDateN.setVisible(!jrbAmi.isSelected());

            jftNom.setText(fA.getNom());
            jftPrenom.setText(fA.getPrenom());
            jftTel.setText(fA.getTel());
            jftAdresse.setText(fA.getAdresse());
            jftCodeP.setText(fA.getCodePostal());
            jftVille.setText(fA.getVille());
            jftMail.setText(fA.getMail());
            jftMobile.setText(fA.getMobile());

        }
        if (f.getType() == 2) {
            Parent fP = (Parent) f;//jcbChContact.getSelectedItem();
            jrbParent.setSelected(true);
            jlbMobile.setVisible(jrbParent.isSelected());
            jftMobile.setVisible(jrbParent.isSelected());
            jlbDateN.setVisible(jrbParent.isSelected());
            jftDateN.setVisible(jrbParent.isSelected());

            jftNom.setText(fP.getNom());
            jftPrenom.setText(fP.getPrenom());
            jftAdresse.setText(fP.getAdresse());
            jftCodeP.setText(fP.getCodePostal());
            jftVille.setText(fP.getVille());
            jftTel.setText(fP.getTel());
            jftMail.setText(fP.getMail());
            jftMobile.setText(fP.getMobile());
            jftDateN.setText(fP.getDateNaiss());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgChoixFiche = new javax.swing.ButtonGroup();
        jrbConnais = new javax.swing.JRadioButton();
        jrbAmi = new javax.swing.JRadioButton();
        jrbParent = new javax.swing.JRadioButton();
        jlbNewContact = new javax.swing.JLabel();
        jlbNom = new javax.swing.JLabel();
        jlbPrenom = new javax.swing.JLabel();
        jlbAdresse = new javax.swing.JLabel();
        jlbCodeP = new javax.swing.JLabel();
        jlbVille = new javax.swing.JLabel();
        jlbTel = new javax.swing.JLabel();
        jlbMail = new javax.swing.JLabel();
        jlbMobile = new javax.swing.JLabel();
        jlbDateN = new javax.swing.JLabel();
        jbModifier = new javax.swing.JButton();
        jftNom = new javax.swing.JFormattedTextField();
        jftPrenom = new javax.swing.JFormattedTextField();
        jftAdresse = new javax.swing.JFormattedTextField();
        jftCodeP = new javax.swing.JFormattedTextField();
        jftVille = new javax.swing.JFormattedTextField();
        jftTel = new javax.swing.JFormattedTextField();
        jftMail = new javax.swing.JFormattedTextField();
        jftMobile = new javax.swing.JFormattedTextField();
        jftDateN = new javax.swing.JFormattedTextField();
        jbSupprimer = new javax.swing.JButton();
        jcbChContact = new javax.swing.JComboBox();
        jbNouveau = new javax.swing.JButton();
        jbQuitter = new javax.swing.JButton();
        jbRefresh = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carnet d'adresse");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bgChoixFiche.add(jrbConnais);
        jrbConnais.setText("Connaissance");
        jrbConnais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbConnaisActionPerformed(evt);
            }
        });

        bgChoixFiche.add(jrbAmi);
        jrbAmi.setText("Ami");
        jrbAmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAmiActionPerformed(evt);
            }
        });

        bgChoixFiche.add(jrbParent);
        jrbParent.setText("Parent");
        jrbParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbParentActionPerformed(evt);
            }
        });

        jlbNewContact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNewContact.setText("Gestion des Contacts");
        jlbNewContact.setToolTipText("créer un nouveau contact");

        jlbNom.setText("Nom");
        jlbNom.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbNom.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbPrenom.setText("Prenom");
        jlbPrenom.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbPrenom.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbAdresse.setText("Adresse : n° / Rue");
        jlbAdresse.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbAdresse.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbCodeP.setText("Code Postal");
        jlbCodeP.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbCodeP.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbVille.setText("Ville");
        jlbVille.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbVille.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbTel.setText("Téléphone");
        jlbTel.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbTel.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbMail.setText("Email");
        jlbMail.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbMail.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbMobile.setText("Mobile");
        jlbMobile.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbMobile.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbDateN.setText("Date de Naissance");
        jlbDateN.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbDateN.setMinimumSize(new java.awt.Dimension(50, 25));

        jbModifier.setText("Modifier");
        jbModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifierActionPerformed(evt);
            }
        });

        jftNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftNomFocusGained(evt);
            }
        });
        jftNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftNomMouseClicked(evt);
            }
        });
        jftNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftNomActionPerformed(evt);
            }
        });

        jftPrenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftPrenomMouseClicked(evt);
            }
        });
        jftPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftPrenomActionPerformed(evt);
            }
        });

        jftTel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftTelMouseClicked(evt);
            }
        });

        jbSupprimer.setText("Supprimer");
        jbSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSupprimerActionPerformed(evt);
            }
        });

        jcbChContact.setModel(initComboBox());
        jcbChContact.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbChContactItemStateChanged(evt);
            }
        });

        jbNouveau.setText("Nouveau");
        jbNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNouveauActionPerformed(evt);
            }
        });

        jbQuitter.setText("Quitter");
        jbQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitterActionPerformed(evt);
            }
        });

        jbRefresh.setText("Refresh");
        jbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshActionPerformed(evt);
            }
        });

        jMFile.setText("File");
        jMFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMFileMouseClicked(evt);
            }
        });

        jMenuItem1.setText("Quitter");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMFile.add(jMenuItem1);

        jMenuBar1.add(jMFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbNewContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNouveau)
                        .addGap(18, 18, 18)
                        .addComponent(jbRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbModifier)
                        .addGap(18, 18, 18)
                        .addComponent(jbSupprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbQuitter))
                    .addComponent(jcbChContact, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbConnais, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jrbAmi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrbParent, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbCodeP, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jlbVille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jlbPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlbAdresse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jlbDateN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jftCodeP)
                            .addComponent(jftVille)
                            .addComponent(jftTel)
                            .addComponent(jftMail)
                            .addComponent(jftNom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jftAdresse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jftDateN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jftMobile, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jlbNewContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbChContact, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbConnais)
                    .addComponent(jrbAmi)
                    .addComponent(jrbParent, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCodeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftCodeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftDateN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDateN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModifier)
                    .addComponent(jbSupprimer)
                    .addComponent(jbNouveau)
                    .addComponent(jbQuitter)
                    .addComponent(jbRefresh))
                .addContainerGap())
        );

        jrbConnais.setSelected(true);
        jlbMobile.setVisible(false);
        jftMobile.setVisible(false);
        jlbDateN.setVisible(false);
jftDateN.setVisible(false);

        setSize(new java.awt.Dimension(595, 623));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbConnaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbConnaisActionPerformed
        jlbMobile.setVisible(!jrbConnais.isSelected());
        jftMobile.setVisible(!jrbConnais.isSelected());
        jlbDateN.setVisible(!jrbConnais.isSelected());
        jftDateN.setVisible(!jrbConnais.isSelected());
    }//GEN-LAST:event_jrbConnaisActionPerformed

    private void jrbAmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAmiActionPerformed
        jlbMobile.setVisible(jrbAmi.isSelected());
        jftMobile.setVisible(jrbAmi.isSelected());
        jlbDateN.setVisible(!jrbAmi.isSelected());
        jftDateN.setVisible(!jrbAmi.isSelected());
    }//GEN-LAST:event_jrbAmiActionPerformed

    private void jrbParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbParentActionPerformed
        jlbMobile.setVisible(jrbParent.isSelected());
        jftMobile.setVisible(jrbParent.isSelected());
        jlbDateN.setVisible(jrbParent.isSelected());
        jftDateN.setVisible(jrbParent.isSelected());
    }//GEN-LAST:event_jrbParentActionPerformed

    private void jbModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifierActionPerformed

        Connaissance f = (Connaissance) jcbChContact.getSelectedItem();

        try {
            f.setNom(jftNom.getText());
        } catch (DataExceptions ex) {
            ex.msgPrint();
        }
        try {
            f.setPrenom(jftPrenom.getText());
        } catch (DataExceptions ex) {
            ex.msgPrint();
        }
        try {
            f.setAdresse(jftAdresse.getText());
        } catch (DataExceptions ex) {
            ex.msgPrint();
        }
        try {
            f.setCodePostal(jftCodeP.getText());
        } catch (DataExceptions ex) {
            ex.msgPrint();
        }
        try {
            f.setVille(jftVille.getText());
        } catch (DataExceptions ex) {
            ex.msgPrint();
        }
        try {
            f.setTel(jftTel.getText());
        } catch (DataExceptions ex) {
            ex.msgPrint();
        }
        try {
            f.setMail(jftMail.getText());
        } catch (DataExceptions ex) {
            ex.msgPrint();
        }
        echange.connect();
        f.save(echange, f.genValue());
        if (jrbConnais.isSelected() && f.getType() != 0) {
            Connaissance ficheN = new Connaissance();
            try {
                ficheN.transform(f);
            } catch (DataExceptions ex) {
                ex.msgPrint();
            }
            jcbChContact.removeItem(jcbChContact.getSelectedItem());
            jcbChContact.addItem(ficheN);
            ficheN.save(echange, ficheN.genValue());
        }
        if (jrbAmi.isSelected() && f.getType() != 1) {
            Ami ficheN = new Ami();
            try {
                ficheN.transform(f);
            } catch (DataExceptions ex) {
                ex.msgPrint();
            }
            try {
                ficheN.setMobile(jftMobile.getText());
            } catch (DataExceptions ex) {
                ex.msgPrint();
            }

            jcbChContact.removeItem(jcbChContact.getSelectedItem());
            jcbChContact.addItem(ficheN);
            ficheN.save(echange, ficheN.genValue());

        }
        if (jrbParent.isSelected() && f.getType() != 2) {
            Parent ficheN = new Parent();
            try {
                ficheN.transform(f);
            } catch (DataExceptions ex) {
                ex.msgPrint();
            }
            try {
                ficheN.setMobile(jftMobile.getText());
            } catch (DataExceptions ex) {
                ex.msgPrint();
            }
            try {
                ficheN.setDateNaiss(jftDateN.getText());
            } catch (DataExceptions ex) {
                ex.msgPrint();
            }
            jcbChContact.removeItem(jcbChContact.getSelectedItem());
            jcbChContact.addItem(ficheN);
            ficheN.save(echange, ficheN.genValue());

        }

        if (f.getType() == 1) {
            Ami sf = (Ami) f;
            try {
                sf.setMobile(jftMobile.getText());
            } catch (DataExceptions ex) {
                ex.msgPrint();
            }
            sf.save(echange, sf.genValue());

        }
        if (f.getType() == 2) {
            Parent sf = (Parent) f;
            try {
                sf.setMobile(jftMobile.getText());
            } catch (DataExceptions ex) {
                ex.msgPrint();
            }
            try {
                sf.setDateNaiss(jftDateN.getText());
            } catch (DataExceptions ex) {
                ex.msgPrint();
            }
            sf.save(echange, sf.genValue());
        }

        carnet.updateC(jcbChContact);
        JOptionPane.showMessageDialog(null, "Le Contact a été modifié", "Modification",
                JOptionPane.QUESTION_MESSAGE);
        echange.close();


    }//GEN-LAST:event_jbModifierActionPerformed

    private void jftNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftNomActionPerformed

    private void jbSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSupprimerActionPerformed
        Connaissance f = (Connaissance) jcbChContact.getSelectedItem();
        int n;
        n = JOptionPane.showConfirmDialog(null, "Etes-vous sûr ?", "Suppression", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (n == 0) {
            echange.connect();
            f.changeActif(echange);
            echange.close();
            jcbChContact.removeItem(jcbChContact.getSelectedItem());
        }

        carnet.updateC(jcbChContact);
    }//GEN-LAST:event_jbSupprimerActionPerformed

    private void jftNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftNomMouseClicked

    }//GEN-LAST:event_jftNomMouseClicked

    private void jftPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftPrenomActionPerformed

    private void jftTelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftTelMouseClicked

    }//GEN-LAST:event_jftTelMouseClicked

    private void jftPrenomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftPrenomMouseClicked

    }//GEN-LAST:event_jftPrenomMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        echange.connect();
//        carnet.save(echange);
//        echange.close();
    }//GEN-LAST:event_formWindowClosing

    private void jcbChContactItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbChContactItemStateChanged
        Connaissance f = (Connaissance) jcbChContact.getSelectedItem();
        if (f != null) {
            afficherF(f);
        }


    }//GEN-LAST:event_jcbChContactItemStateChanged

    private void jbNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNouveauActionPerformed
        Formulaire formulaire = new Formulaire();
        formulaire.setVisible(true);
    }//GEN-LAST:event_jbNouveauActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_formFocusGained

    private void jbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshActionPerformed
        // TODO add your handling code here:
//        echange.connect();
//        Carnet carn = new Carnet();
//        carn.restore(echange);
//        echange.close();

        jcbChContact.removeAllItems();
//        for(int i = 0; i < carn.taille(); i++){
//        jcbChContact.addItem(carn.recup(i));
//        }

        jcbChContact.setModel(initComboBox());
    }//GEN-LAST:event_jbRefreshActionPerformed

    private void jbQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbQuitterActionPerformed

    private void jftNomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftNomFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jftNomFocusGained

    private void jMFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMFileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMFileMouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        //System.exit(0);
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgChoixFiche;
    private javax.swing.JMenu jMFile;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jbModifier;
    private javax.swing.JButton jbNouveau;
    private javax.swing.JButton jbQuitter;
    private javax.swing.JButton jbRefresh;
    private javax.swing.JButton jbSupprimer;
    private javax.swing.JComboBox jcbChContact;
    private javax.swing.JFormattedTextField jftAdresse;
    private javax.swing.JFormattedTextField jftCodeP;
    private javax.swing.JFormattedTextField jftDateN;
    private javax.swing.JFormattedTextField jftMail;
    private javax.swing.JFormattedTextField jftMobile;
    private javax.swing.JFormattedTextField jftNom;
    private javax.swing.JFormattedTextField jftPrenom;
    private javax.swing.JFormattedTextField jftTel;
    private javax.swing.JFormattedTextField jftVille;
    private javax.swing.JLabel jlbAdresse;
    private javax.swing.JLabel jlbCodeP;
    private javax.swing.JLabel jlbDateN;
    private javax.swing.JLabel jlbMail;
    private javax.swing.JLabel jlbMobile;
    private javax.swing.JLabel jlbNewContact;
    private javax.swing.JLabel jlbNom;
    private javax.swing.JLabel jlbPrenom;
    private javax.swing.JLabel jlbTel;
    private javax.swing.JLabel jlbVille;
    private javax.swing.JRadioButton jrbAmi;
    private javax.swing.JRadioButton jrbConnais;
    private javax.swing.JRadioButton jrbParent;
    // End of variables declaration//GEN-END:variables
}
