package fenetre;

import carnet.Carnet;
import connexion.Echange;
import exceptions.DataExceptions;
import fiche.*;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Formulaire extends javax.swing.JFrame {

        FormMod parent = (FormMod) this.getParent();
        Echange echange = parent.getEchange();
        Carnet carnet = parent.getCarnet();

    public Formulaire() {
        initComponents();
        

        
        
//        echange.connect();
//        try {
//            carnet.restore(echange);
//        } catch (DataExceptions ex) {
//            ex.msgPrint();
//        }
//        echange.close();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgChoixFiche = new javax.swing.ButtonGroup();
        jrbConnais = new javax.swing.JRadioButton();
        jrbAmi = new javax.swing.JRadioButton();
        jrbParent = new javax.swing.JRadioButton();
        jlbNewContact = new javax.swing.JLabel();
        jlbNom = new javax.swing.JLabel();
        jlbPrenom = new javax.swing.JLabel();
        jlbAdresse = new javax.swing.JLabel();
        jlbCodeP = new javax.swing.JLabel();
        jlbVille = new javax.swing.JLabel();
        jlbTel = new javax.swing.JLabel();
        jlbMail = new javax.swing.JLabel();
        jlbMobile = new javax.swing.JLabel();
        jlbDateN = new javax.swing.JLabel();
        jbAjouter = new javax.swing.JButton();
        jftNom = new javax.swing.JFormattedTextField();
        jftPrenom = new javax.swing.JFormattedTextField();
        jftAdresse = new javax.swing.JFormattedTextField();
        jftCodeP = new javax.swing.JFormattedTextField();
        jftVille = new javax.swing.JFormattedTextField();
        jftTel = new javax.swing.JFormattedTextField();
        jftMail = new javax.swing.JFormattedTextField();
        jftMobile = new javax.swing.JFormattedTextField();
        jftDateN = new javax.swing.JFormattedTextField();
        jbAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulaire Nouveau Contact");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bgChoixFiche.add(jrbConnais);
        jrbConnais.setText("Connaissance");
        jrbConnais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbConnaisActionPerformed(evt);
            }
        });

        bgChoixFiche.add(jrbAmi);
        jrbAmi.setText("Ami");
        jrbAmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAmiActionPerformed(evt);
            }
        });

        bgChoixFiche.add(jrbParent);
        jrbParent.setText("Parent");
        jrbParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbParentActionPerformed(evt);
            }
        });

        jlbNewContact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNewContact.setText("Nouveau Contact");
        jlbNewContact.setToolTipText("créer un nouveau contact");

        jlbNom.setText("Nom");
        jlbNom.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbNom.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbPrenom.setText("Prenom");
        jlbPrenom.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbPrenom.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbAdresse.setText("Adresse : n° / Rue");
        jlbAdresse.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbAdresse.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbCodeP.setText("Code Postal");
        jlbCodeP.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbCodeP.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbVille.setText("Ville");
        jlbVille.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbVille.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbTel.setText("Téléphone");
        jlbTel.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbTel.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbMail.setText("Email");
        jlbMail.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbMail.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbMobile.setText("Mobile");
        jlbMobile.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbMobile.setMinimumSize(new java.awt.Dimension(50, 25));

        jlbDateN.setText("Date de Naissance");
        jlbDateN.setMaximumSize(new java.awt.Dimension(50, 25));
        jlbDateN.setMinimumSize(new java.awt.Dimension(50, 25));

        jbAjouter.setText("Ajouter");
        jbAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjouterActionPerformed(evt);
            }
        });

        jftNom.setText("Obligatoire");
        jftNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftNomFocusGained(evt);
            }
        });
        jftNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftNomMouseClicked(evt);
            }
        });
        jftNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftNomActionPerformed(evt);
            }
        });

        jftPrenom.setText("Obligatoire");
        jftPrenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftPrenomFocusGained(evt);
            }
        });
        jftPrenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftPrenomMouseClicked(evt);
            }
        });
        jftPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftPrenomActionPerformed(evt);
            }
        });

        jftTel.setText("Obligatoire");
        jftTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftTelFocusGained(evt);
            }
        });
        jftTel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftTelMouseClicked(evt);
            }
        });

        jbAnnuler.setText("Fermer");
        jbAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbNewContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jrbConnais, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jrbAmi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jrbParent, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbCodeP, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jlbVille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jlbPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlbAdresse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlbDateN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftPrenom)
                            .addComponent(jftCodeP)
                            .addComponent(jftVille)
                            .addComponent(jftTel)
                            .addComponent(jftMail)
                            .addComponent(jftNom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jftAdresse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jftDateN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jftMobile, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAjouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAnnuler)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbNewContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbParent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrbConnais)
                        .addComponent(jrbAmi)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCodeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftCodeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftDateN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDateN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAjouter)
                    .addComponent(jbAnnuler))
                .addContainerGap())
        );

        jrbConnais.setSelected(true);
        jlbMobile.setVisible(false);
        jftMobile.setVisible(false);
        jlbDateN.setVisible(false);
jftDateN.setVisible(false);

        setSize(new java.awt.Dimension(588, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbConnaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbConnaisActionPerformed
        jlbMobile.setVisible(!jrbConnais.isSelected());
        jftMobile.setVisible(!jrbConnais.isSelected());
        jlbDateN.setVisible(!jrbConnais.isSelected());
        jftDateN.setVisible(!jrbConnais.isSelected());
    }//GEN-LAST:event_jrbConnaisActionPerformed

    private void jrbAmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAmiActionPerformed
        jlbMobile.setVisible(jrbAmi.isSelected());
        jftMobile.setVisible(jrbAmi.isSelected());
        jlbDateN.setVisible(!jrbAmi.isSelected());
        jftDateN.setVisible(!jrbAmi.isSelected());
    }//GEN-LAST:event_jrbAmiActionPerformed

    private void jrbParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbParentActionPerformed
        jlbMobile.setVisible(jrbParent.isSelected());
        jftMobile.setVisible(jrbParent.isSelected());
        jlbDateN.setVisible(jrbParent.isSelected());
        jftDateN.setVisible(jrbParent.isSelected());
    }//GEN-LAST:event_jrbParentActionPerformed

    private void jbAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjouterActionPerformed
        if (jftNom.getText().equals("") || jftPrenom.getText().equals("")
                || jftTel.getText().equals("") || jftNom.getText().equals("Obligatoire")
                || jftPrenom.getText().equals("Obligatoire")
                || jftTel.getText().equals("Obligatoire")) {
            JOptionPane.showMessageDialog(null,
                    "les champs Nom, Prénom et Téléphone sont obligatoires",
                    "Champs Obligatoires", JOptionPane.ERROR_MESSAGE);

        } else {

            if (jrbConnais.isSelected()) {
                Connaissance fiche = new Connaissance();//jftNom.getText(), jftPrenom.getText(), jftTel.getText());
                fiche.setActif(1);
                try {
                    fiche.setNom(jftNom.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setPrenom(jftPrenom.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setTel(jftTel.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setAdresse(jftAdresse.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setCodePostal(jftCodeP.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setVille(jftVille.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setMail(jftMail.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }

                carnet.ajout(fiche);
                echange.connect();
                fiche.save(echange, fiche.genValue());
                echange.close();
            }

            if (jrbAmi.isSelected()) {
                Ami fiche = new Ami();//jftNom.getText(), jftPrenom.getText(), jftTel.getText());
                fiche.setActif(1);
                try {
                    fiche.setNom(jftNom.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setPrenom(jftPrenom.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setTel(jftTel.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setAdresse(jftAdresse.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setCodePostal(jftCodeP.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setVille(jftVille.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setMail(jftMail.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setMobile(jftMobile.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }

                carnet.ajout(fiche);
                echange.connect();
                fiche.save(echange, fiche.genValue());
                echange.close();
            }

            if (jrbParent.isSelected()) {
                Parent fiche = new Parent();//jftNom.getText(), jftPrenom.getText(), jftTel.getText());
                fiche.setActif(1);
                try {
                    fiche.setNom(jftNom.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setPrenom(jftPrenom.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setTel(jftTel.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setAdresse(jftAdresse.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setCodePostal(jftCodeP.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setVille(jftVille.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setMail(jftMail.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setMobile(jftMobile.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }
                try {
                    fiche.setDateNaiss(jftDateN.getText());
                } catch (DataExceptions ex) {
                    ex.msgPrint();
                }

                carnet.ajout(fiche);
                echange.connect();
                fiche.save(echange, fiche.genValue());
                echange.close();
            }
            JOptionPane.showMessageDialog(null, "Le contact a été ajouté", "Ajout", JOptionPane.INFORMATION_MESSAGE);
            jftNom.setText("Obligatoire");
            jftPrenom.setText("Obligatoire");
            jftAdresse.setText(null);
            jftCodeP.setText(null);
            jftVille.setText(null);
            jftTel.setText("Obligatoire");
            jftMail.setText(null);
            jftMobile.setText(null);
            jftDateN.setText(null);
        }


    }//GEN-LAST:event_jbAjouterActionPerformed

    private void jftNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftNomActionPerformed

    private void jbAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnnulerActionPerformed

        this.dispose();

    }//GEN-LAST:event_jbAnnulerActionPerformed

    private void jftNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftNomMouseClicked
        if (jftNom.getText().equalsIgnoreCase("Obligatoire")) {
            jftNom.setText("");
        }
    }//GEN-LAST:event_jftNomMouseClicked

    private void jftPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftPrenomActionPerformed

    private void jftTelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftTelMouseClicked
        if (jftTel.getText().equalsIgnoreCase("Obligatoire")) {
            jftTel.setText("");
        }
    }//GEN-LAST:event_jftTelMouseClicked

    private void jftPrenomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftPrenomMouseClicked
        if (jftPrenom.getText().equalsIgnoreCase("Obligatoire")) {
            jftPrenom.setText("");
        }
    }//GEN-LAST:event_jftPrenomMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        echange.connect();
//        carnet.save(echange);
//        echange.close();
    }//GEN-LAST:event_formWindowClosing

    private void jftNomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftNomFocusGained
        if (jftNom.getText().equalsIgnoreCase("Obligatoire")) {
            jftNom.setText("");
        }
    }//GEN-LAST:event_jftNomFocusGained

    private void jftPrenomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftPrenomFocusGained
        if (jftPrenom.getText().equalsIgnoreCase("Obligatoire")) {
            jftPrenom.setText("");
        }
    }//GEN-LAST:event_jftPrenomFocusGained

    private void jftTelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftTelFocusGained
        if (jftTel.getText().equalsIgnoreCase("Obligatoire")) {
            jftTel.setText("");
        }
    }//GEN-LAST:event_jftTelFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgChoixFiche;
    private javax.swing.JButton jbAjouter;
    private javax.swing.JButton jbAnnuler;
    private javax.swing.JFormattedTextField jftAdresse;
    private javax.swing.JFormattedTextField jftCodeP;
    private javax.swing.JFormattedTextField jftDateN;
    private javax.swing.JFormattedTextField jftMail;
    private javax.swing.JFormattedTextField jftMobile;
    private javax.swing.JFormattedTextField jftNom;
    private javax.swing.JFormattedTextField jftPrenom;
    private javax.swing.JFormattedTextField jftTel;
    private javax.swing.JFormattedTextField jftVille;
    private javax.swing.JLabel jlbAdresse;
    private javax.swing.JLabel jlbCodeP;
    private javax.swing.JLabel jlbDateN;
    private javax.swing.JLabel jlbMail;
    private javax.swing.JLabel jlbMobile;
    private javax.swing.JLabel jlbNewContact;
    private javax.swing.JLabel jlbNom;
    private javax.swing.JLabel jlbPrenom;
    private javax.swing.JLabel jlbTel;
    private javax.swing.JLabel jlbVille;
    private javax.swing.JRadioButton jrbAmi;
    private javax.swing.JRadioButton jrbConnais;
    private javax.swing.JRadioButton jrbParent;
    // End of variables declaration//GEN-END:variables
}
